#!/bin/sh
#set -e
pushd ~/github.com/nixos-configs
#nano configuration.nix
alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch -I ~/github.com/nixos-configs/configuration.nix &>nixos-switch.log || (
 cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
popd
